### PR TITLE
Ensure GitHub Action runs in specified version of node

### LINKED ISSUE #1000: [11.5.0] Error: error:0308010C:digital envelope routines::unsupported
**Bug report**

[We currently use `chromaui/action@v11` for running Chromatic in GitHub Actions](https://github.com/danskernesdigitalebibliotek/dpl-design-system/blob/develop/.github/workflows/chromatic.yml). After v11.5.0 was released and the version of the action was bumped automatically the action has started to fail with the error below in seemingly unrelated PRs. 

As far as I can tell no other elements in the workflow was changed.

Example of a failing PR: https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/653

After locking the action at 11.4.0 the error no longer occurs: https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/654

The error code is the same as in #720 which is about a year old.

```
node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/home/runner/work/dpl-design-system/dpl-design-system/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/runner/work/dpl-design-system/dpl-design-system/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/runner/work/dpl-design-system/dpl-design-system/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/runner/work/dpl-design-system/dpl-design-system/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/runner/work/dpl-design-system/dpl-design-system/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/runner/work/dpl-design-system/dpl-design-system/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/runner/work/dpl-design-system/dpl-design-system/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /home/runner/work/dpl-design-system/dpl-design-system/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at /home/runner/work/dpl-design-system/dpl-design-system/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

### LINKED ISSUE #1002: The engine "node" is incompatible with this module. Expected version "18.16.1". Got "20.8.1"
**Bug report**

Previously our action was working fine. As of this morning I'm getting the following error.

## Error

```bash
The CLI tried to run your build-storybook script, but the command failed. This indicates a problem with your Storybook. Here's what to do:
    → Command failed: yarn run build-storybook --output-dir /tmp/chromatic--1759-SARwqzIUwEU0 --webpack-stats-json /tmp/chromatic--1759-SARwqzIUwEU0
- Check the Storybook build log printed below.
- Run npm run build-storybook or yarn build-storybook yourself and make sure it outputs a valid Storybook by opening the generated index.html in your browser.
- Review the build-storybook CLI options at https://storybook.js.org/docs/configurations/cli-options/#for-build-storybook
Command failed with exit code 1: yarn run build-storybook --output-dir /tmp/chromatic--17[59]-SARwqzIUwEU0 --webpack-stats-json /tmp/chromatic--1759-SARwqzIUwEU0
error: The engine "node" is incompatible with this module. Expected version "18.16.1". Got "20.8.1"
error Commands cannot run with an incompatible environment.
ℹ Build command:
yarn run build-storybook --output-dir /tmp/chromatic--1759-SARwqzIUwEU0 --webpack-stats-json /tmp/chromatic--1759-SARwqzIUwEU0
ℹ Runtime metadata:
{
  "nodePlatform": "linux",
  "nodeVersion": "20.8.1",
  "packageManager": "yarn",
  "packageManagerVersion": "1.22.22"
}
ℹ Storybook build output:
```

## GitHub Action

```yml
  visual-tests:
    needs: [interaction-tests, changed-files]
    if: ${{ needs.changed-files.outputs.any_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18.16.1
      - run: yarn
      - uses: chromaui/action@v1
        with:
          node-version: 18.16.1
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyChanged: true
          exitZeroOnChanges: true
```

### PR DESCRIPTION
**Pull request by tevanoff**
Revert this small bit that was added in #991.

It was not necessary for the change made in that PR, and it caused the Storybook build command to run with the node version [specified by the GitHub Action](https://github.com/chromaui/chromatic-cli/blob/a1fb89f970745a6e55288603c09bf2015bb47766/action.yml#L151) (node 20), instead of the version of node that is installed in the workflow using something like `actions/setup-node`.

Fixes #1000
Fixes #1002

<details>
  <summary>📦 Published PR as canary version: <code>11.5.4--canary.1006.9485918262.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install chromatic@11.5.4--canary.1006.9485918262.0
  # or 
  yarn add chromatic@11.5.4--canary.1006.9485918262.0
  ```
</details>

### CODE REVIEW

**Review by ethriel3695 — APPROVED** [review]
I get the correct Node version run on my end, and Chromatic also succeeds, even though the Node version does not match. I also get a green Chromatic run.
Screenshot 2024-06-11 at 18 30 29
Screenshot 2024-06-11 at 18 31 37

File: node-src/tasks/build.ts [hunk 1]
```diff
@@ -122,7 +122,8 @@ export const buildStorybook = async (ctx: Context) => {
 
     const subprocess = execaCommand(ctx.buildCommand, {
       stdio: [null, logFile, null],
-      preferLocal: true,
+      preferLocal: false, // When true, this will run in the node version set
+                          // by the action (node20), not the version set in the workflow
```
Comment (ghengeveld) [inline node-src/tasks/build.ts:126]:
```suggestion
      // When true, this will run in the Node version set by the
      // action (node20), not the version set in the workflow.
      preferLocal: false,
```

**Review by ghengeveld — APPROVED** [review]

**Comment by ghengeveld** [comment]
:rocket: PR was released in [`v11.5.4`](https://github.com/chromaui/chromatic-cli/releases/tag/v11.5.4) :rocket:
